ALTER TABLE cars ADD COLUMN IF NOT EXISTS body_style VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS drivetrain VARCHAR(50);

UPDATE cars SET body_style = 'SUV' WHERE make IN ('Honda','BMW','Chevrolet','Subaru','Jeep','Toyota','Nissan','Hyundai','Kia','Mazda','Volkswagen','Audi','Mercedes-Benz','Lexus','Acura','Infiniti','Volvo','Land Rover','Ford','GMC','Dodge','Ram','Buick','Cadillac','Lincoln','Mitsubishi','Tesla') AND model IN ('CR-V','Pilot','X5','X3','X1','X7','Tahoe','Suburban','Outback','Forester','Crosstrek','Ascent','RAV4','Highlander','4Runner','Sequoia','Grand Cherokee','Wrangler','Cherokee','Escape','Explorer','Expedition','Edge','Bronco','Equinox','Traverse','Yukon','Acadia','Enclave','Escalade','Navigator','RX','NX','GX','QX60','QX80','MDX','RDX','XC90','XC60','Q5','Q7','Q3','Tiguan','Atlas','Sportage','Sorento','Telluride','Santa Fe','Tucson','Palisade','CX-5','CX-9','Outlander','Eclipse Cross');
UPDATE cars SET body_style = 'Sedan' WHERE make IN ('Toyota','Honda','Nissan','Hyundai','Kia','Mazda','Subaru','Volkswagen','Audi','BMW','Mercedes-Benz','Lexus','Acura','Infiniti','Genesis','Volvo','Jaguar','Tesla','Chevrolet','Ford','Dodge','Chrysler','Buick','Cadillac','Lincoln','Mitsubishi') AND model IN ('Camry','Corolla','Accord','Civic','Altima','Sentra','Maxima','Elantra','Sonata','Optima','Forte','Mazda3','Mazda6','Impreza','Legacy','Jetta','Passat','A4','A6','A3','3 Series','5 Series','7 Series','C-Class','E-Class','S-Class','CLA','ES','IS','LS','TLX','ILX','Q50','Q70','G70','G80','G90','S60','S90','XE','XF','Model 3','Model S','Malibu','Impala','Fusion','Charger','300','Regal','LaCrosse','CT4','CT5','Continental','Mirage');
UPDATE cars SET body_style = 'Coupe' WHERE make IN ('Ford','Chevrolet','Dodge','BMW','Mercedes-Benz','Audi','Nissan','Toyota','Subaru','Hyundai','Honda') AND model IN ('Mustang','Camaro','Challenger','2 Series','4 Series','A5','S5','GT-R','Z','86','BRZ','Veloster','Civic Coupe','Supra','GR86','M2','M4');
UPDATE cars SET body_style = 'Wagon' WHERE make IN ('Subaru','Volvo','Audi','Mercedes-Benz','BMW','Volkswagen','Buick') AND model IN ('Outback','V90','V60','A4 Allroad','A6 Allroad','E-Class Wagon','3 Series Touring','5 Series Touring','Golf SportWagen','Regal TourX');
UPDATE cars SET body_style = 'Convertible' WHERE make IN ('Mazda','BMW','Mercedes-Benz','Audi','Porsche','Ford','Chevrolet','Jeep','Mini','Fiat','Volkswagen','Nissan') AND model IN ('MX-5','Miata','Z4','SL','A5 Cabriolet','718','911','Mustang Convertible','Camaro Convertible','Wrangler','Wrangler Unlimited','Mini Cooper Convertible','124 Spider','Eos','370Z Roadster');
UPDATE cars SET body_style = 'Hatchback' WHERE make IN ('Honda','Mazda','Toyota','Volkswagen','Hyundai','Kia','Ford','Chevrolet','Mini','Subaru','Nissan') AND model IN ('Fit','Mazda3','Corolla Hatchback','Golf','GTI','R','Elantra GT','i30','Rio','Fiesta','Focus','Sonic','Spark','Cooper Hardtop','Impreza Hatchback','Versa Note');
UPDATE cars SET body_style = 'Truck' WHERE make IN ('Ford','Chevrolet','GMC','Ram','Toyota','Nissan','Honda','Jeep','Hyundai','Rivian','Tesla') AND model IN ('F-150','Ranger','Maverick','Silverado','Colorado','Sierra','Canyon','1500','2500','3500','Tundra','Tacoma','Frontier','Titan','Ridgeline','Gladiator','Santa Cruz','R1T','Cybertruck','Lightning');
UPDATE cars SET body_style = 'Van' WHERE make IN ('Honda','Toyota','Chrysler','Dodge','Kia','Nissan','Mercedes-Benz','Ford') AND model IN ('Odyssey','Sienna','Pacifica','Grand Caravan','Carnival','NV','Metris','Sprinter','Transit');

UPDATE cars SET body_style = COALESCE(body_style, 'Sedan') WHERE body_style IS NULL;
