ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_tier_id INTEGER REFERENCES subscription_tiers(id) DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS listings_used INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dealership_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_period_end TIMESTAMP;

UPDATE users SET subscription_tier_id = 1 WHERE subscription_tier_id IS NULL;
